import { Role } from '../generate';

export const ROLES_ALLOWED_TO_CREATE = [
  Role.KEY_ACCOUNT_MANAGER,
  Role.ACCOUNT_MANAGER,
  Role.ADMIN,
];

export const ROLES_ALLOWED_TO_UPLOAD_FILE = [
  Role.DESIGNER,
  Role.KEY_ACCOUNT_MANAGER,
  Role.ACCOUNT_MANAGER,
  Role.PURCHASER,
  Role.PRODUCT_DEVELOPER,
  Role.ADMIN,
];

export const ROLES_ALLOWED_TO_EDIT_PD = [
  Role.KEY_ACCOUNT_MANAGER,
  Role.ACCOUNT_MANAGER,
  Role.PURCHASER,
  Role.PRODUCT_DEVELOPER,
  Role.ADMIN,
];

export const ROLES_ALLOWED_TO_ADD_REMOVE_SOURCING = [
  Role.KEY_ACCOUNT_MANAGER,
  Role.ACCOUNT_MANAGER,
  Role.PURCHASER,
  Role.PRODUCT_DEVELOPER,
  Role.ADMIN,
];

export const ROLES_ALLOWED_SEE_PRODUCTION = [
  Role.KEY_ACCOUNT_MANAGER,
  Role.ACCOUNT_MANAGER,
  Role.PURCHASER,
  Role.PRODUCT_DEVELOPER,
  Role.ADMIN,
];

export const ROLES_ALLOWED_SEE_SOURCING = [
  Role.KEY_ACCOUNT_MANAGER,
  Role.ACCOUNT_MANAGER,
  Role.PURCHASER,
  Role.PRODUCT_DEVELOPER,
  Role.ADMIN,
];

export const ROLES_ALLOWED_SEE_CALCULATION = [
  Role.KEY_ACCOUNT_MANAGER,
  Role.ACCOUNT_MANAGER,
  Role.PURCHASER,
  Role.ADMIN,
];
export const ROLES_ALLOWED_TO_CHANGE_CLOSED = [Role.ADMIN];
