const REMIX_ICONS = {
  CLASS_NAMES: {
    ADD_LINE: 'ri-add-line',
    ALERT_LINE: 'ri-alert-line',
    ARROW_DOWN_S_FILL: 'ri-arrow-down-s-fill',
    ARROW_DOWN_S_LINE: 'ri-arrow-down-s-line',
    ARROW_LEFT_LINE: 'ri-arrow-left-line',
    ARROW_LEFT_RIGHT_LINE: 'ri-arrow-left-right-line',
    ARROW_RIGHT_LINE: 'ri-arrow-right-line',
    CALCULATOR_LINE: 'ri-calculator-line',
    CAMERA_LINE: 'ri-camera-line',
    CHECK_LINE: 'ri-check-line',
    CLOSE_CIRCLE_LINE: 'ri-close-circle-line',
    CLOSE_LINE: 'ri-close-line',
    DELETE_BIN_6_LINE: 'ri-delete-bin-6-line',
    DELETE_BIN_LINE: 'ri-delete-bin-line',
    DOWNLOAD_LINE: 'ri-download-line',
    EDIT_LINE: 'ri-edit-line',
    ERROR_WARNING_FILL: 'ri-error-warning-fill',
    FILE_3_LINE: 'ri-file-3-line',
    FILE_COPY_LINE: 'ri-file-copy-line',
    HISTORY_LINE: 'ri-history-line',
    LINE_CHART_LINE: 'ri-line-chart-line',
    LINK_UNLINK_M: 'ri-link-unlink-m',
    LOADER_2_LINE: 'ri-loader-2-line',
    MESSAGE_2_LINE: 'ri-message-2-line',
    MORE_LINE: 'ri-more-line',
    SAVE_LINE: 'ri-save-line',
    TOGGLE_LINE: 'ri-toggle-line',
    ARROW_UP_LINE: 'ri-arrow-up-line',
    ARROW_DOWN_LINE: 'ri-arrow-down-line',
    UPLOAD_2_LINE: 'ri-upload-2-line',
  },
};

export default REMIX_ICONS;
