enum QueryKeysEnum {
  SearchProfiles = 'SearchProfiles',
  Overview = 'Overview',
  Clients = 'Clients',
  Members = 'Members',
  SourcingCompanies = 'SourcingCompanies',
  Vendors = 'Vendors',
  Productions = 'Productions',
  ProductDevelopment = 'ProductDevelopment',
  ProductDevelopmentDeep = 'ProductDevelopmentDeep',
  ProductDevelopmentImage = 'ProductDevelopmentImage',
  FoldingType = 'FoldingType',
  PriceCalculation = 'PriceCalculation',
  ItemCategory = 'ItemCategory',
  ProductGroup = 'ProductGroup',
  Projects = 'Projects',
  OpComp = 'OpComp',
  Option = 'Option',
  User = 'User',
  Changes = 'Changes',
  Currency = 'Currency',
  SourcingQty = 'SourcingQty',
  Attachments = 'Attachments',
  DefaultValues = 'DefaultValues',
  Navigation = 'Navigation',
}

export default QueryKeysEnum;
